DATA_DIR: "/Users/noah/Desktop/Marsden/files"
FILE_LIST: "/Users/noah/Desktop/Marsden/files_clean.txt"

NAME: "googlenet_c30_clean_point_small"
TRAINER: "base"
PREDICTOR: "base"
EVALUATION: "base"
MODEL: "GoogleNet"
POST_PROCESSOR: "POINT"
DATASET:    "axial2d_point"
RESULTS_DIR: "./results"
LOG_FILE: "/Users/noah/Desktop/Marsden/sv_ml/results/googlenet_c30_train300k_clean_point_small_shortened/log/train.txt"

ITER_FILE: "/Users/noah/Desktop/Marsden/sv_ml/results/googlenet_c30_train300k_clean_point_small_shortened/log/iter.txt"

MODEL_DIR: "/Users/noah/Desktop/Marsden/sv_ml/results/googlenet_c30_train300k_clean_point_small_shortened/model"
MODEL_NAME: "googlenet"
MODEL_TYPE: "googlenet"

LOG_STEP: 2000
LEAK: 0.2
BATCH_SIZE: 4
LEARNING_RATE: 0.00005
TRAIN_STEPS: 300000
BATCH_SIZE: 4
L2_REG: 0.0
NUM_FILTERS: 32

IMAGE_TYPE: "BLUR"
BLUR_SIGMA: 3

AUGMENT: true
AUGMENT_FACTOR: 10
AUGMENT_R_SCALE: 0.65
CENTER: true

INPUT_DIMS:
  - 160
  - 160
  - 1

BALANCE_RADIUS: false
R_SMALL: 0.75
N_SAMPLE: 10000

SPACING: 0.029
DIMS: 240
CENTER_DIMS: 200
CROP_DIMS: 160
NUM_CHANNELS: 1
NUM_CONTOUR_POINTS: 30

DROPOUT: 0.6

INIT: 'xavier'



VAL_PATTERNS:
  - OSMSC0110_CLEAN
  - cabg5_CLEAN
  - OSMSC0082_CLEAN
  - OSMSC0003_CLEAN

TEST_PATTERNS:
  - OSMSC0006
  - OSMSC0080
  - OSMSC0083
  - OSMSC0101
  - OSMSC0110
  - OSMSC0171
  - OSMSC0178
  - OSMSC0119
  - OSMSC0144
  - OSMSC0148
  - OSMSC0150
  - OSMSC0170
  - OSMSC0177
  - cabg11

TRAIN_PATTERNS:
  - OSMSC0001
  - OSMSC0002
  - OSMSC0004
  - OSMSC0005
